<?php

namespace Database\Seeders;

use App\Models\Equipment;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class AlibatonRealEquipmentSeeder extends Seeder
{
    /**
     * Seed official equipment catalog and fleet from Alibaton Construction Incorporated (https://alibaton.com.ph/)
     * Real Philippine market equipment specifications, commercial rental rates, and purchase values.
     */
    public function run(): void
    {
        $fleet = [
            // =========================================================================
            // 1. LUFFING TOWER CRANES (Alibaton Core Specialization for Urban Sites)
            // =========================================================================
            [
                'code' => 'ALIB-TC-L140-8',
                'name' => 'JHD140N-8 Luffing Jib Tower Crane',
                'crane_model' => 'JHD140N-8',
                'category' => 'tower_crane',
                'crane_category' => 'luffing',
                'description' => 'Alibaton flagship 8-Ton luffing tower crane designed for high-density urban corridors and narrow sites with restricted boundary airspaces.',
                'rental_rate' => 320000.00,
                'rental_unit' => 'month',
                'status' => 'rented',
                'serial_number' => 'ALIB-L140-2023-01',
                'acquisition_date' => Carbon::parse('2023-02-15'),
                'purchase_price' => 11500000.00,
                'current_value' => 10200000.00,
                'quantity_available' => 1,
                'location' => 'BGC Uptown Tower Site, Taguig City',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/luffing-tower-crane.jpg',
                'specifications' => 'Max Capacity: 8 t | Max Working Radius: 50 m | Tip Load: 1.8 t @ 50m | Hook Height: 140 m | Hoist Mechanism: 45 kW Frequency Inverter',
                'maximum_load' => 8.00,
                'maximum_load_unit' => 'tons',
                'maximum_radius' => 50.00,
                'maximum_radius_unit' => 'm',
                'final_height' => 140.00,
                'final_height_unit' => 'm',
                'rental_services' => ['operator_and_riggers', 'erection_and_dismantling', 'telescoping_climbing', 'maintenance_and_repair', 'logistic'],
            ],
            [
                'code' => 'ALIB-TC-L140-10',
                'name' => 'JHD140N-10 Luffing Jib Tower Crane',
                'crane_model' => 'JHD140N-10',
                'category' => 'tower_crane',
                'crane_category' => 'luffing',
                'description' => 'Heavy-duty 10-Ton luffing crane configuration optimized for commercial high-rises with tight clearance between adjacent structures.',
                'rental_rate' => 360000.00,
                'rental_unit' => 'month',
                'status' => 'available',
                'serial_number' => 'ALIB-L140-2023-02',
                'acquisition_date' => Carbon::parse('2023-05-10'),
                'purchase_price' => 13200000.00,
                'current_value' => 11800000.00,
                'quantity_available' => 1,
                'location' => 'Alibaton Equipment Depot, Quezon City Yard',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/luffing-tower-crane.jpg',
                'specifications' => 'Max Capacity: 10 t | Max Working Radius: 50 m | Tip Load: 2.2 t @ 50m | Hook Height: 140 m | Slewing Speed: 0-0.7 r/min',
                'maximum_load' => 10.00,
                'maximum_load_unit' => 'tons',
                'maximum_radius' => 50.00,
                'maximum_radius_unit' => 'm',
                'final_height' => 140.00,
                'final_height_unit' => 'm',
                'rental_services' => ['operator_and_riggers', 'erection_and_dismantling', 'telescoping_climbing', 'maintenance_and_repair'],
            ],
            [
                'code' => 'ALIB-TC-L190-12',
                'name' => 'JHD190A-12 Luffing Jib Tower Crane',
                'crane_model' => 'JHD190A-12',
                'category' => 'tower_crane',
                'crane_category' => 'luffing',
                'description' => '12-Ton high-capacity luffing crane engineered for precast element hoisting and core wall erection on towers exceeding 45 floors.',
                'rental_rate' => 450000.00,
                'rental_unit' => 'month',
                'status' => 'rented',
                'serial_number' => 'ALIB-L190-2023-03',
                'acquisition_date' => Carbon::parse('2023-08-22'),
                'purchase_price' => 16500000.00,
                'current_value' => 15000000.00,
                'quantity_available' => 1,
                'location' => 'Ortigas Center High-Rise Project, Pasig City',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/luffing-tower-crane.jpg',
                'specifications' => 'Max Capacity: 12 t | Max Working Radius: 55 m | Tip Load: 2.5 t @ 55m | Hook Height: 160 m | Hoist Mechanism: 60 kW VVVF',
                'maximum_load' => 12.00,
                'maximum_load_unit' => 'tons',
                'maximum_radius' => 55.00,
                'maximum_radius_unit' => 'm',
                'final_height' => 160.00,
                'final_height_unit' => 'm',
                'rental_services' => ['operator_and_riggers', 'erection_and_dismantling', 'telescoping_climbing', 'maintenance_and_repair', 'logistic'],
            ],
            [
                'code' => 'ALIB-TC-L190-14',
                'name' => 'JHD190A-14 Luffing Jib Tower Crane',
                'crane_model' => 'JHD190A-14',
                'category' => 'tower_crane',
                'crane_category' => 'luffing',
                'description' => '14-Ton reinforced luffing crane with high-speed winch and variable frequency drive for rapid concrete bucket cycle times.',
                'rental_rate' => 520000.00,
                'rental_unit' => 'month',
                'status' => 'available',
                'serial_number' => 'ALIB-L190-2023-04',
                'acquisition_date' => Carbon::parse('2023-11-14'),
                'purchase_price' => 18800000.00,
                'current_value' => 17400000.00,
                'quantity_available' => 1,
                'location' => 'Alibaton Equipment Depot, Quezon City Yard',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/luffing-tower-crane.jpg',
                'specifications' => 'Max Capacity: 14 t | Max Working Radius: 55 m | Tip Load: 2.8 t @ 55m | Hook Height: 160 m | Heavy Duty Mast Section',
                'maximum_load' => 14.00,
                'maximum_load_unit' => 'tons',
                'maximum_radius' => 55.00,
                'maximum_radius_unit' => 'm',
                'final_height' => 160.00,
                'final_height_unit' => 'm',
                'rental_services' => ['operator_and_riggers', 'maintenance_and_repair', 'erection_and_dismantling'],
            ],
            [
                'code' => 'ALIB-TC-L200-16',
                'name' => 'JHD200C-16 Luffing Jib Tower Crane',
                'crane_model' => 'JHD200C-16',
                'category' => 'tower_crane',
                'crane_category' => 'luffing',
                'description' => '16-Ton high-rise luffing crane suited for composite steel-concrete construction and heavy MEP plant hoisting at roof levels.',
                'rental_rate' => 630000.00,
                'rental_unit' => 'month',
                'status' => 'rented',
                'serial_number' => 'ALIB-L200-2024-01',
                'acquisition_date' => Carbon::parse('2024-01-18'),
                'purchase_price' => 23500000.00,
                'current_value' => 22000000.00,
                'quantity_available' => 1,
                'location' => 'Cebu IT Park Prime Tower Site, Cebu City',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/luffing-tower-crane.jpg',
                'specifications' => 'Max Capacity: 16 t | Max Working Radius: 55 m | Tip Load: 3.2 t @ 55m | Hook Height: 170 m | Full Climber Kit Included',
                'maximum_load' => 16.00,
                'maximum_load_unit' => 'tons',
                'maximum_radius' => 55.00,
                'maximum_radius_unit' => 'm',
                'final_height' => 170.00,
                'final_height_unit' => 'm',
                'rental_services' => ['operator_and_riggers', 'erection_and_dismantling', 'telescoping_climbing', 'maintenance_and_repair'],
            ],
            [
                'code' => 'ALIB-TC-L300-18',
                'name' => 'JHD300C-18 Luffing Jib Tower Crane',
                'crane_model' => 'JHD300C-18',
                'category' => 'tower_crane',
                'crane_category' => 'luffing',
                'description' => '18-Ton heavy-capacity luffing crane with extended 60-meter radius designed for mega mixed-use towers and hospital complexes.',
                'rental_rate' => 750000.00,
                'rental_unit' => 'month',
                'status' => 'available',
                'serial_number' => 'ALIB-L300-2024-02',
                'acquisition_date' => Carbon::parse('2024-03-20'),
                'purchase_price' => 28000000.00,
                'current_value' => 26800000.00,
                'quantity_available' => 1,
                'location' => 'Valenzuela Heavy Equipment Yard',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/luffing-tower-crane.jpg',
                'specifications' => 'Max Capacity: 18 t | Max Working Radius: 60 m | Tip Load: 3.5 t @ 60m | Hook Height: 180 m | High Performance Inverter Control',
                'maximum_load' => 18.00,
                'maximum_load_unit' => 'tons',
                'maximum_radius' => 60.00,
                'maximum_radius_unit' => 'm',
                'final_height' => 180.00,
                'final_height_unit' => 'm',
                'rental_services' => ['operator_and_riggers', 'erection_and_dismantling', 'telescoping_climbing', 'maintenance_and_repair', 'logistic'],
            ],
            [
                'code' => 'ALIB-TC-SCM-D125',
                'name' => 'SCM D125 Luffing Jib Tower Crane',
                'crane_model' => 'SCM D125',
                'category' => 'tower_crane',
                'crane_category' => 'luffing',
                'description' => 'Alibaton project-tested SCM 10-Ton luffing crane featured in premium high-rise condominium projects across Metro Manila.',
                'rental_rate' => 380000.00,
                'rental_unit' => 'month',
                'status' => 'rented',
                'serial_number' => 'SCM-D125-2022-09',
                'acquisition_date' => Carbon::parse('2022-09-12'),
                'purchase_price' => 14200000.00,
                'current_value' => 12400000.00,
                'quantity_available' => 1,
                'location' => 'Makati CBD Residential Tower Site',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/condominium-project.jpg',
                'specifications' => 'Max Capacity: 10 t | Jib Length: 50 m | Hook Under Hook: 145 m | Proven track record on Manila condominium developments',
                'maximum_load' => 10.00,
                'maximum_load_unit' => 'tons',
                'maximum_radius' => 50.00,
                'maximum_radius_unit' => 'm',
                'final_height' => 145.00,
                'final_height_unit' => 'm',
                'rental_services' => ['operator_and_riggers', 'erection_and_dismantling', 'telescoping_climbing', 'maintenance_and_repair'],
            ],
            [
                'code' => 'ALIB-TC-POT-MR608',
                'name' => 'Potain MR608 Heavy Luffing Tower Crane',
                'crane_model' => 'Potain MR608',
                'category' => 'tower_crane',
                'crane_category' => 'luffing',
                'description' => 'Heavy industrial 32-Ton luffing tower crane by Potain Manitowoc, deployed on major factory, power, and heavy manufacturing installations.',
                'rental_rate' => 1150000.00,
                'rental_unit' => 'month',
                'status' => 'rented',
                'serial_number' => 'POT-MR608-2023-01',
                'acquisition_date' => Carbon::parse('2023-04-05'),
                'purchase_price' => 38500000.00,
                'current_value' => 35500000.00,
                'quantity_available' => 1,
                'location' => 'Heavy Industrial Manufacturing Plant Site, Batangas',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/project-factory-2.jpg',
                'specifications' => 'Max Capacity: 32 t | Jib Length: 60 m | Hook Under Hook: 51.6 m | Engineered for massive industrial assemblies and boilers',
                'maximum_load' => 32.00,
                'maximum_load_unit' => 'tons',
                'maximum_radius' => 60.00,
                'maximum_radius_unit' => 'm',
                'final_height' => 65.00,
                'final_height_unit' => 'm',
                'rental_services' => ['operator_and_riggers', 'maintenance_and_repair', 'erection_and_dismantling', 'engineering_consultancy'],
            ],

            // =========================================================================
            // 2. TOPLESS / FLAT-TOP TOWER CRANES (Fast Erection & Multi-Crane Overlapping)
            // =========================================================================
            [
                'code' => 'ALIB-TC-T6013-6',
                'name' => 'JHT6013N-6 Topless Tower Crane',
                'crane_model' => 'JHT6013N-6',
                'category' => 'tower_crane',
                'crane_category' => 'flat_top',
                'description' => 'Versatile 6-Ton flat-top crane with 60-meter radius, ideal for overlapping multi-crane layouts on commercial estates.',
                'rental_rate' => 280000.00,
                'rental_unit' => 'month',
                'status' => 'available',
                'serial_number' => 'ALIB-T6013-2023-01',
                'acquisition_date' => Carbon::parse('2023-03-11'),
                'purchase_price' => 8800000.00,
                'current_value' => 7800000.00,
                'quantity_available' => 2,
                'location' => 'Alibaton Equipment Depot, Quezon City Yard',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/topless-tower-crane.jpg',
                'specifications' => 'Max Capacity: 6 t | Max Working Radius: 60 m | Tip Load: 1.3 t @ 60m | Hook Height: 140 m | Modular Flat-Top Quick Jib Assembly',
                'maximum_load' => 6.00,
                'maximum_load_unit' => 'tons',
                'maximum_radius' => 60.00,
                'maximum_radius_unit' => 'm',
                'final_height' => 140.00,
                'final_height_unit' => 'm',
                'rental_services' => ['operator_and_riggers', 'maintenance_and_repair', 'erection_and_dismantling', 'logistic'],
            ],
            [
                'code' => 'ALIB-TC-T6017-8',
                'name' => 'JHT6017N-8 Topless Tower Crane',
                'crane_model' => 'JHT6017N-8',
                'category' => 'tower_crane',
                'crane_category' => 'flat_top',
                'description' => '8-Ton topless crane with reinforced jib chords, delivering 1.7t tip load at 60m radius for fast-track building projects.',
                'rental_rate' => 330000.00,
                'rental_unit' => 'month',
                'status' => 'rented',
                'serial_number' => 'ALIB-T6017-2023-02',
                'acquisition_date' => Carbon::parse('2023-06-19'),
                'purchase_price' => 10500000.00,
                'current_value' => 9400000.00,
                'quantity_available' => 1,
                'location' => 'Clark Global City Commercial Complex, Pampanga',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/topless-tower-crane.jpg',
                'specifications' => 'Max Capacity: 8 t | Max Working Radius: 60 m | Tip Load: 1.7 t @ 60m | Hook Height: 140 m | Frequency Controlled Hoisting',
                'maximum_load' => 8.00,
                'maximum_load_unit' => 'tons',
                'maximum_radius' => 60.00,
                'maximum_radius_unit' => 'm',
                'final_height' => 140.00,
                'final_height_unit' => 'm',
                'rental_services' => ['operator_and_riggers', 'erection_and_dismantling', 'maintenance_and_repair'],
            ],
            [
                'code' => 'ALIB-TC-T6515-10',
                'name' => 'JHT6515N-10 Topless Tower Crane',
                'crane_model' => 'JHT6515N-10',
                'category' => 'tower_crane',
                'crane_category' => 'flat_top',
                'description' => '10-Ton extended 65-meter jib topless crane, built for large-footprint mixed-use retail and residential podium projects.',
                'rental_rate' => 410000.00,
                'rental_unit' => 'month',
                'status' => 'available',
                'serial_number' => 'ALIB-T6515-2023-03',
                'acquisition_date' => Carbon::parse('2023-09-02'),
                'purchase_price' => 13800000.00,
                'current_value' => 12500000.00,
                'quantity_available' => 1,
                'location' => 'Alibaton Equipment Depot, Quezon City Yard',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/topless-tower-crane.jpg',
                'specifications' => 'Max Capacity: 10 t | Max Working Radius: 65 m | Tip Load: 1.5 t @ 65m | Hook Height: 150 m | Intelligent Anti-Collision Interface',
                'maximum_load' => 10.00,
                'maximum_load_unit' => 'tons',
                'maximum_radius' => 65.00,
                'maximum_radius_unit' => 'm',
                'final_height' => 150.00,
                'final_height_unit' => 'm',
                'rental_services' => ['operator_and_riggers', 'maintenance_and_repair', 'erection_and_dismantling', 'logistic'],
            ],
            [
                'code' => 'ALIB-TC-T7025-12',
                'name' => 'JHT7025A-12 Topless Tower Crane',
                'crane_model' => 'JHT7025A-12',
                'category' => 'tower_crane',
                'crane_category' => 'flat_top',
                'description' => '12-Ton topless crane with extensive 70m jib coverage and 2.5t tip load capacity for heavy infrastructure and hospital developments.',
                'rental_rate' => 490000.00,
                'rental_unit' => 'month',
                'status' => 'rented',
                'serial_number' => 'ALIB-T7025-2024-01',
                'acquisition_date' => Carbon::parse('2024-01-25'),
                'purchase_price' => 17200000.00,
                'current_value' => 16100000.00,
                'quantity_available' => 1,
                'location' => 'New Manila Airport Access Viaduct Depot, Bulacan',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/topless-tower-crane.jpg',
                'specifications' => 'Max Capacity: 12 t | Max Working Radius: 70 m | Tip Load: 2.5 t @ 70m | Hook Height: 160 m | Heavy Wind Rating Design',
                'maximum_load' => 12.00,
                'maximum_load_unit' => 'tons',
                'maximum_radius' => 70.00,
                'maximum_radius_unit' => 'm',
                'final_height' => 160.00,
                'final_height_unit' => 'm',
                'rental_services' => ['operator_and_riggers', 'erection_and_dismantling', 'maintenance_and_repair', 'logistic'],
            ],
            [
                'code' => 'ALIB-TC-T7527-16',
                'name' => 'JHT7527C-16 Topless Tower Crane',
                'crane_model' => 'JHT7527C-16',
                'category' => 'tower_crane',
                'crane_category' => 'flat_top',
                'description' => '16-Ton heavy topless crane featuring 75-meter jib radius for transit stations, precast yards, and railway terminal structures.',
                'rental_rate' => 640000.00,
                'rental_unit' => 'month',
                'status' => 'available',
                'serial_number' => 'ALIB-T7527-2024-02',
                'acquisition_date' => Carbon::parse('2024-02-14'),
                'purchase_price' => 22000000.00,
                'current_value' => 20800000.00,
                'quantity_available' => 1,
                'location' => 'Valenzuela Heavy Equipment Yard',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/topless-tower-crane.jpg',
                'specifications' => 'Max Capacity: 16 t | Max Working Radius: 75 m | Tip Load: 2.7 t @ 75m | Hook Height: 170 m | High Capacity Drum Winch',
                'maximum_load' => 16.00,
                'maximum_load_unit' => 'tons',
                'maximum_radius' => 75.00,
                'maximum_radius_unit' => 'm',
                'final_height' => 170.00,
                'final_height_unit' => 'm',
                'rental_services' => ['operator_and_riggers', 'maintenance_and_repair', 'erection_and_dismantling'],
            ],
            [
                'code' => 'ALIB-TC-T8024-20',
                'name' => 'JHT8024B-20 Topless Tower Crane',
                'crane_model' => 'JHT8024B-20',
                'category' => 'tower_crane',
                'crane_category' => 'flat_top',
                'description' => 'Flagship 20-Ton topless crane with exceptional 80-meter jib reach, engineered for mega bridge pylons and cement silos.',
                'rental_rate' => 780000.00,
                'rental_unit' => 'month',
                'status' => 'available',
                'serial_number' => 'ALIB-T8024-2024-03',
                'acquisition_date' => Carbon::parse('2024-04-10'),
                'purchase_price' => 27500000.00,
                'current_value' => 26200000.00,
                'quantity_available' => 1,
                'location' => 'Valenzuela Heavy Equipment Yard',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/topless-tower-crane.jpg',
                'specifications' => 'Max Capacity: 20 t | Max Working Radius: 80 m | Tip Load: 2.4 t @ 80m | Hook Height: 180 m | 75 kW Inverter Hoist System',
                'maximum_load' => 20.00,
                'maximum_load_unit' => 'tons',
                'maximum_radius' => 80.00,
                'maximum_radius_unit' => 'm',
                'final_height' => 180.00,
                'final_height_unit' => 'm',
                'rental_services' => ['operator_and_riggers', 'maintenance_and_repair', 'erection_and_dismantling', 'logistic'],
            ],
            [
                'code' => 'ALIB-TC-POT-MCT385',
                'name' => 'Potain MCT385 Topless Tower Crane',
                'crane_model' => 'Potain MCT385',
                'category' => 'tower_crane',
                'crane_category' => 'flat_top',
                'description' => 'High-capacity 20-Ton Potain topless tower crane with 75m jib, as deployed on major cement plant and heavy infrastructure projects.',
                'rental_rate' => 790000.00,
                'rental_unit' => 'month',
                'status' => 'rented',
                'serial_number' => 'POT-MCT385-2023-01',
                'acquisition_date' => Carbon::parse('2023-07-28'),
                'purchase_price' => 29000000.00,
                'current_value' => 27000000.00,
                'quantity_available' => 1,
                'location' => 'Republic Cement Plant Expansion Site, Bulacan',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/project-cement-plant-2.jpg',
                'specifications' => 'Max Capacity: 20 t | Jib Length: 75 m | Hook Under Hook: 131.7 m | Manitowoc Potain high precision frequency control',
                'maximum_load' => 20.00,
                'maximum_load_unit' => 'tons',
                'maximum_radius' => 75.00,
                'maximum_radius_unit' => 'm',
                'final_height' => 135.00,
                'final_height_unit' => 'm',
                'rental_services' => ['operator_and_riggers', 'maintenance_and_repair', 'erection_and_dismantling'],
            ],
            [
                'code' => 'ALIB-TC-POT-MCT328',
                'name' => 'Potain MCT328 L16 Topless Tower Crane',
                'crane_model' => 'Potain MCT328 L16',
                'category' => 'tower_crane',
                'crane_category' => 'flat_top',
                'description' => '16-Ton Potain topless crane deployed on the North-South Commuter Railway (NSCR) viaduct and station contracts.',
                'rental_rate' => 630000.00,
                'rental_unit' => 'month',
                'status' => 'rented',
                'serial_number' => 'POT-MCT328-2023-02',
                'acquisition_date' => Carbon::parse('2023-05-18'),
                'purchase_price' => 21800000.00,
                'current_value' => 20000000.00,
                'quantity_available' => 1,
                'location' => 'NSCR Railway Station Contract 01, Malolos, Bulacan',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/railway-project-feedback.jpg',
                'specifications' => 'Max Capacity: 16 t | Jib Length: 75 m | Hook Under Hook: 52.1 m | Approved for Department of Transportation rail corridor works',
                'maximum_load' => 16.00,
                'maximum_load_unit' => 'tons',
                'maximum_radius' => 75.00,
                'maximum_radius_unit' => 'm',
                'final_height' => 60.00,
                'final_height_unit' => 'm',
                'rental_services' => ['operator_and_riggers', 'maintenance_and_repair', 'erection_and_dismantling', 'logistic'],
            ],
            [
                'code' => 'ALIB-TC-POT-MCT278',
                'name' => 'Potain MCT278 K12 Topless Tower Crane',
                'crane_model' => 'Potain MCT278 K12',
                'category' => 'tower_crane',
                'crane_category' => 'flat_top',
                'description' => '12-Ton Potain topless tower crane deployed on Metro Manila Subway Project shaft sites and water reclamation facilities.',
                'rental_rate' => 480000.00,
                'rental_unit' => 'month',
                'status' => 'rented',
                'serial_number' => 'POT-MCT278-2023-03',
                'acquisition_date' => Carbon::parse('2023-08-30'),
                'purchase_price' => 16500000.00,
                'current_value' => 15200000.00,
                'quantity_available' => 1,
                'location' => 'Metro Manila Subway CP101 Shaft Site, Valenzuela',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/project-subway.jpg',
                'specifications' => 'Max Capacity: 12 t | Jib Length: 70 m | Hook Under Hook: 47.6 m | Engineered for deep underground shaft hoisting and logistics',
                'maximum_load' => 12.00,
                'maximum_load_unit' => 'tons',
                'maximum_radius' => 70.00,
                'maximum_radius_unit' => 'm',
                'final_height' => 55.00,
                'final_height_unit' => 'm',
                'rental_services' => ['operator_and_riggers', 'maintenance_and_repair', 'erection_and_dismantling'],
            ],

            // =========================================================================
            // 3. HAMMERHEAD TOWER CRANES (Proven Industry Workhorses)
            // =========================================================================
            [
                'code' => 'ALIB-TC-POT-MC200A',
                'name' => 'Potain MC200A Hammerhead Tower Crane',
                'crane_model' => 'Potain MC200A',
                'category' => 'tower_crane',
                'crane_category' => 'hammerhead',
                'description' => '10-Ton reliable hammerhead tower crane with proven heavy industrial performance, featured in Alibaton cement plant portfolio.',
                'rental_rate' => 390000.00,
                'rental_unit' => 'month',
                'status' => 'rented',
                'serial_number' => 'POT-MC200A-2022-04',
                'acquisition_date' => Carbon::parse('2022-07-15'),
                'purchase_price' => 12800000.00,
                'current_value' => 11200000.00,
                'quantity_available' => 1,
                'location' => 'Holcim Cement Plant Upgrade Site, Norzagaray, Bulacan',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/project-cement-plant-1.jpg',
                'specifications' => 'Max Capacity: 10 t | Jib Length: 60 m | Hook Under Hook: 130 m | Standard ACEL Philippine rating workhorse',
                'maximum_load' => 10.00,
                'maximum_load_unit' => 'tons',
                'maximum_radius' => 60.00,
                'maximum_radius_unit' => 'm',
                'final_height' => 130.00,
                'final_height_unit' => 'm',
                'rental_services' => ['operator_and_riggers', 'maintenance_and_repair', 'erection_and_dismantling'],
            ],
            [
                'code' => 'ALIB-TC-POT-MC200B',
                'name' => 'Potain MC200B Hammerhead Tower Crane',
                'crane_model' => 'Potain MC200B',
                'category' => 'tower_crane',
                'crane_category' => 'hammerhead',
                'description' => '10-Ton Potain hammerhead tower crane utilized in subway excavation launching shafts and commercial complexes.',
                'rental_rate' => 390000.00,
                'rental_unit' => 'month',
                'status' => 'rented',
                'serial_number' => 'POT-MC200B-2022-05',
                'acquisition_date' => Carbon::parse('2022-10-10'),
                'purchase_price' => 12800000.00,
                'current_value' => 11400000.00,
                'quantity_available' => 1,
                'location' => 'Metro Manila Subway North Station Site, Quezon City',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/project-subway.jpg',
                'specifications' => 'Max Capacity: 10 t | Jib Length: 60 m | Hook Under Hook: 59.7 m | Heavy winch for continuous soil and muck box lifting',
                'maximum_load' => 10.00,
                'maximum_load_unit' => 'tons',
                'maximum_radius' => 60.00,
                'maximum_radius_unit' => 'm',
                'final_height' => 65.00,
                'final_height_unit' => 'm',
                'rental_services' => ['operator_and_riggers', 'maintenance_and_repair', 'logistic'],
            ],
            [
                'code' => 'ALIB-TC-POT-MC175',
                'name' => 'Potain MC175 Hammerhead Tower Crane',
                'crane_model' => 'Potain MC175',
                'category' => 'tower_crane',
                'crane_category' => 'hammerhead',
                'description' => '10-Ton hammerhead tower crane with 55m jib reach, featured in Alibaton’s Royal Pacific Residence high-rise development.',
                'rental_rate' => 360000.00,
                'rental_unit' => 'month',
                'status' => 'rented',
                'serial_number' => 'POT-MC175-2022-02',
                'acquisition_date' => Carbon::parse('2022-04-20'),
                'purchase_price' => 11900000.00,
                'current_value' => 10500000.00,
                'quantity_available' => 1,
                'location' => 'Royal Pacific Residence Site, Manila Bay Area',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/royal-pacific-residence.jpg',
                'specifications' => 'Max Capacity: 10 t | Jib Length: 55 m | Hook Under Hook: 101 m | Optimized for coastal conditions and tall residential towers',
                'maximum_load' => 10.00,
                'maximum_load_unit' => 'tons',
                'maximum_radius' => 55.00,
                'maximum_radius_unit' => 'm',
                'final_height' => 105.00,
                'final_height_unit' => 'm',
                'rental_services' => ['operator_and_riggers', 'maintenance_and_repair', 'telescoping_climbing'],
            ],
            [
                'code' => 'ALIB-TC-POT-MC320',
                'name' => 'Potain MC320A K12 Hammerhead Tower Crane',
                'crane_model' => 'Potain MC320A K12',
                'category' => 'tower_crane',
                'crane_category' => 'hammerhead',
                'description' => '12-Ton Potain heavy hammerhead tower crane with 70m jib, deployed on railway station construction and heavy transport corridors.',
                'rental_rate' => 490000.00,
                'rental_unit' => 'month',
                'status' => 'available',
                'serial_number' => 'POT-MC320-2023-01',
                'acquisition_date' => Carbon::parse('2023-03-22'),
                'purchase_price' => 17000000.00,
                'current_value' => 15500000.00,
                'quantity_available' => 1,
                'location' => 'Alibaton Equipment Depot, Quezon City Yard',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/railway-project-feedback.jpg',
                'specifications' => 'Max Capacity: 12 t | Jib Length: 70 m | Hook Under Hook: 46.4 m | Heavy structural framework for rail & bridge viaducts',
                'maximum_load' => 12.00,
                'maximum_load_unit' => 'tons',
                'maximum_radius' => 70.00,
                'maximum_radius_unit' => 'm',
                'final_height' => 55.00,
                'final_height_unit' => 'm',
                'rental_services' => ['operator_and_riggers', 'erection_and_dismantling', 'maintenance_and_repair'],
            ],
            [
                'code' => 'ALIB-TC-POT-MC205B',
                'name' => 'Potain MC205B Hammerhead Tower Crane',
                'crane_model' => 'Potain MC205B',
                'category' => 'tower_crane',
                'crane_category' => 'hammerhead',
                'description' => '10-Ton commercial building tower crane deployed on institutional, commercial, and factory developments in Luzon.',
                'rental_rate' => 390000.00,
                'rental_unit' => 'month',
                'status' => 'rented',
                'serial_number' => 'POT-MC205B-2022-07',
                'acquisition_date' => Carbon::parse('2022-11-08'),
                'purchase_price' => 13000000.00,
                'current_value' => 11600000.00,
                'quantity_available' => 1,
                'location' => 'Alabang Corporate Center Development, Muntinlupa',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/project-commercial.jpg',
                'specifications' => 'Max Capacity: 10 t | Jib Length: 60 m | Hook Under Hook: 59 m | High reliability for medium to high-rise building shells',
                'maximum_load' => 10.00,
                'maximum_load_unit' => 'tons',
                'maximum_radius' => 60.00,
                'maximum_radius_unit' => 'm',
                'final_height' => 65.00,
                'final_height_unit' => 'm',
                'rental_services' => ['operator_and_riggers', 'maintenance_and_repair', 'logistic'],
            ],
            [
                'code' => 'ALIB-TC-POT-MC170',
                'name' => 'Potain MC170 Hammerhead Tower Crane',
                'crane_model' => 'Potain MC170',
                'category' => 'tower_crane',
                'crane_category' => 'hammerhead',
                'description' => '10-Ton mid-rise condominium specialist crane, compact footprint with fast turnaround and efficient power consumption.',
                'rental_rate' => 350000.00,
                'rental_unit' => 'month',
                'status' => 'available',
                'serial_number' => 'POT-MC170-2021-09',
                'acquisition_date' => Carbon::parse('2021-12-05'),
                'purchase_price' => 11200000.00,
                'current_value' => 9600000.00,
                'quantity_available' => 1,
                'location' => 'Alibaton Equipment Depot, Quezon City Yard',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/project-mid-rise.jpg',
                'specifications' => 'Max Capacity: 10 t | Jib Length: 55 m | Hook Under Hook: 29 m | Free standing height for rapid low/mid-rise deployment',
                'maximum_load' => 10.00,
                'maximum_load_unit' => 'tons',
                'maximum_radius' => 55.00,
                'maximum_radius_unit' => 'm',
                'final_height' => 35.00,
                'final_height_unit' => 'm',
                'rental_services' => ['operator_and_riggers', 'maintenance_and_repair'],
            ],

            // =========================================================================
            // 4. CONSTRUCTION HOISTS & VERTICAL ACCESS (Personnel & Material Transport)
            // =========================================================================
            [
                'code' => 'ALIB-HST-SC200',
                'name' => 'SCM SC200/200 Twin Cage Construction Hoist',
                'crane_model' => 'SCM SC200/200 Twin',
                'category' => 'construction_hoist',
                'crane_category' => 'hoist',
                'description' => 'Dual-cage construction elevator (2,000 kg per cage) for rapid vertical transport of manpower and finishing materials up to 200 meters.',
                'rental_rate' => 160000.00,
                'rental_unit' => 'month',
                'status' => 'rented',
                'serial_number' => 'SCM-SC200-2023-01',
                'acquisition_date' => Carbon::parse('2023-02-10'),
                'purchase_price' => 3600000.00,
                'current_value' => 3200000.00,
                'quantity_available' => 2,
                'location' => 'BGC Corporate Tower Site, Taguig City',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/construction-hoist.jpg',
                'specifications' => 'Rated Payload: 2 x 2,000 kg (up to 48 persons) | Lifting Speed: 36-63 m/min VFD | Max Height: 200 m | Cage: 3.2m x 1.5m x 2.5m',
                'maximum_load' => 4.00,
                'maximum_load_unit' => 'tons',
                'final_height' => 200.00,
                'final_height_unit' => 'm',
                'rental_services' => ['operator_and_riggers', 'erection_and_dismantling', 'maintenance_and_repair'],
            ],
            [
                'code' => 'ALIB-HST-SC100',
                'name' => 'Alibaton SC100 Single Cage Material Hoist',
                'crane_model' => 'SC100 Single Cage',
                'category' => 'construction_hoist',
                'crane_category' => 'hoist',
                'description' => 'Single cage 1,000 kg vertical material hoist for mid-rise construction, renovation, and exterior facade access.',
                'rental_rate' => 95000.00,
                'rental_unit' => 'month',
                'status' => 'available',
                'serial_number' => 'ALIB-SC100-2023-02',
                'acquisition_date' => Carbon::parse('2023-05-14'),
                'purchase_price' => 1950000.00,
                'current_value' => 1750000.00,
                'quantity_available' => 2,
                'location' => 'Alibaton Equipment Depot, Quezon City Yard',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/construction-hoist.jpg',
                'specifications' => 'Rated Payload: 1,000 kg | Speed: 33 m/min | Max Height: 100 m | Interlocked safety doors and centrifugal overspeed brake',
                'maximum_load' => 1.00,
                'maximum_load_unit' => 'tons',
                'final_height' => 100.00,
                'final_height_unit' => 'm',
                'rental_services' => ['operator_and_riggers', 'maintenance_and_repair'],
            ],

            // =========================================================================
            // 5. GANTRY CRANES (Yard Logistics, Ports, Precast Casting Yards)
            // =========================================================================
            [
                'code' => 'ALIB-GNT-MG50',
                'name' => 'MG 50-Ton Double Girder Rail-Mounted Gantry Crane',
                'crane_model' => 'MG 50T-32M',
                'category' => 'gantry_crane',
                'crane_category' => 'gantry',
                'description' => 'Heavy rail-mounted gantry crane with 32-meter span for handling heavy precast railway girders, bridge spans, and steel yards.',
                'rental_rate' => 350000.00,
                'rental_unit' => 'month',
                'status' => 'rented',
                'serial_number' => 'MG-50T-2023-01',
                'acquisition_date' => Carbon::parse('2023-01-20'),
                'purchase_price' => 8200000.00,
                'current_value' => 7400000.00,
                'quantity_available' => 1,
                'location' => 'NSCR Railway Precast Girder Casting Yard, Calumpit, Bulacan',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/gantry-crane.jpg',
                'specifications' => 'Rated Capacity: 50 t | Span: 32 m | Lifting Height: 12 m | Rail Travel Speed: 20 m/min | Heavy dual trolley configuration',
                'maximum_load' => 50.00,
                'maximum_load_unit' => 'tons',
                'maximum_radius' => 32.00,
                'maximum_radius_unit' => 'm',
                'final_height' => 12.00,
                'final_height_unit' => 'm',
                'rental_services' => ['operator_and_riggers', 'maintenance_and_repair', 'erection_and_dismantling'],
            ],
            [
                'code' => 'ALIB-GNT-MH20',
                'name' => 'MH 20-Ton Single Girder Gantry Crane',
                'crane_model' => 'MH 20T-24M',
                'category' => 'gantry_crane',
                'crane_category' => 'gantry',
                'description' => '20-Ton overhead yard gantry crane for loading and unloading structural steel, shipping containers, and heavy machinery parts.',
                'rental_rate' => 220000.00,
                'rental_unit' => 'month',
                'status' => 'available',
                'serial_number' => 'MH-20T-2023-02',
                'acquisition_date' => Carbon::parse('2023-06-15'),
                'purchase_price' => 4600000.00,
                'current_value' => 4100000.00,
                'quantity_available' => 1,
                'location' => 'Alibaton Equipment Depot, Quezon City Yard',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/gantry-crane.jpg',
                'specifications' => 'Rated Capacity: 20 t | Span: 24 m | Lifting Height: 9 m | Wireless pendant remote and cabin control options',
                'maximum_load' => 20.00,
                'maximum_load_unit' => 'tons',
                'maximum_radius' => 24.00,
                'maximum_radius_unit' => 'm',
                'final_height' => 9.00,
                'final_height_unit' => 'm',
                'rental_services' => ['operator_and_riggers', 'maintenance_and_repair'],
            ],

            // =========================================================================
            // 6. MOBILE CRANES & BOOM TRUCKS (Fast Mobilization & Heavy Rigging)
            // =========================================================================
            [
                'code' => 'ALIB-MC-SANY250',
                'name' => 'Sany SAC2500S 250-Ton All-Terrain Mobile Crane',
                'crane_model' => 'Sany SAC2500S',
                'category' => 'mobile_crane',
                'crane_category' => 'all_terrain',
                'description' => 'Flagship 250-Ton heavy all-terrain crane featuring 73-meter U-shaped main boom, 43m fixed jib, and multi-steering axles.',
                'rental_rate' => 90000.00,
                'rental_unit' => 'day',
                'status' => 'available',
                'serial_number' => 'SN-SAC250-2024-01',
                'acquisition_date' => Carbon::parse('2024-01-10'),
                'purchase_price' => 34500000.00,
                'current_value' => 32800000.00,
                'quantity_available' => 1,
                'location' => 'Valenzuela Heavy Equipment Yard',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/mobile-crane.jpg',
                'specifications' => 'Max Capacity: 250 t @ 3m | Telescopic Boom: 73 m | Total Jib: 43 m | Max Tip Height: 105 m | 5-Axle Steer-Drive Carrier',
                'maximum_load' => 250.00,
                'maximum_load_unit' => 'tons',
                'maximum_radius' => 78.00,
                'maximum_radius_unit' => 'm',
                'final_height' => 105.00,
                'final_height_unit' => 'm',
                'rental_services' => ['operator_and_riggers', 'maintenance_and_repair', 'logistic', 'engineering_consultancy'],
            ],
            [
                'code' => 'ALIB-MC-TAD80',
                'name' => 'Tadano GR-800EX 80-Ton Rough Terrain Crane',
                'crane_model' => 'Tadano GR-800EX',
                'category' => 'mobile_crane',
                'crane_category' => 'rough_terrain',
                'description' => '80-Ton rough terrain crane with 47m 5-section telescopic boom, ideal for refinery expansions, bridge works, and soft-ground sites.',
                'rental_rate' => 42000.00,
                'rental_unit' => 'day',
                'status' => 'available',
                'serial_number' => 'TD-GR800-2023-09',
                'acquisition_date' => Carbon::parse('2023-08-12'),
                'purchase_price' => 16800000.00,
                'current_value' => 15200000.00,
                'quantity_available' => 1,
                'location' => 'Alibaton Equipment Depot, Quezon City Yard',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/mobile-crane.jpg',
                'specifications' => 'Max Capacity: 80 t @ 3m | Boom Length: 12.0m - 47.0m | Jib: 10.1m - 17.7m | 4x4x4 All-Wheel Drive and Steering',
                'maximum_load' => 80.00,
                'maximum_load_unit' => 'tons',
                'maximum_radius' => 47.00,
                'maximum_radius_unit' => 'm',
                'final_height' => 62.00,
                'final_height_unit' => 'm',
                'rental_services' => ['operator_and_riggers', 'maintenance_and_repair', 'logistic'],
            ],
            [
                'code' => 'ALIB-MC-XCMG50',
                'name' => 'XCMG QY50KA 50-Ton Truck Mounted Crane',
                'crane_model' => 'XCMG QY50KA',
                'category' => 'mobile_crane',
                'crane_category' => 'truck_crane',
                'description' => '50-Ton highway-compliant truck crane for swift mobilization across Philippine road networks to assist tower crane installations.',
                'rental_rate' => 28000.00,
                'rental_unit' => 'day',
                'status' => 'rented',
                'serial_number' => 'XCMG-QY50-2023-05',
                'acquisition_date' => Carbon::parse('2023-04-18'),
                'purchase_price' => 9200000.00,
                'current_value' => 8400000.00,
                'quantity_available' => 2,
                'location' => 'Metro Manila Subway Station Site, Pasig',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/mobile-crane.jpg',
                'specifications' => 'Max Capacity: 50 t @ 3m | 5-Section Octagonal Boom: 43.5 m | Jib: 16 m | Weichai Euro V Diesel Engine',
                'maximum_load' => 50.00,
                'maximum_load_unit' => 'tons',
                'maximum_radius' => 40.00,
                'maximum_radius_unit' => 'm',
                'final_height' => 58.00,
                'final_height_unit' => 'm',
                'rental_services' => ['operator_and_riggers', 'maintenance_and_repair', 'logistic'],
            ],
            [
                'code' => 'ALIB-MC-KATO25',
                'name' => 'Kato KR-25H 25-Ton City Rough Terrain Crane',
                'crane_model' => 'Kato KR-25H',
                'category' => 'mobile_crane',
                'crane_category' => 'rough_terrain',
                'description' => '25-Ton compact city crane engineered for tight access inside industrial compounds, substations, and bridge abutments.',
                'rental_rate' => 18000.00,
                'rental_unit' => 'day',
                'status' => 'available',
                'serial_number' => 'KT-KR25-2022-11',
                'acquisition_date' => Carbon::parse('2022-11-20'),
                'purchase_price' => 5200000.00,
                'current_value' => 4600000.00,
                'quantity_available' => 2,
                'location' => 'Alibaton Equipment Depot, Quezon City Yard',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/mobile-crane.jpg',
                'specifications' => 'Max Capacity: 25 t @ 3.5m | Boom Length: 30.5 m | Compact Outrigger footprint: 6.6m spread | Japanese Hydraulic Reliability',
                'maximum_load' => 25.00,
                'maximum_load_unit' => 'tons',
                'maximum_radius' => 28.00,
                'maximum_radius_unit' => 'm',
                'final_height' => 32.00,
                'final_height_unit' => 'm',
                'rental_services' => ['operator_and_riggers', 'maintenance_and_repair'],
            ],
            [
                'code' => 'ALIB-LOG-ISZ-15T',
                'name' => 'Isuzu Giga 10-Wheeler 15T Telescopic Boom Truck',
                'crane_model' => 'Isuzu Giga 15T Boom Truck',
                'category' => 'transportation',
                'crane_category' => 'boom_truck',
                'description' => 'Heavy transport cargo truck with 15-Ton rear-mounted telescopic crane for self-loading, transport, and offloading of steel and equipment.',
                'rental_rate' => 18000.00,
                'rental_unit' => 'day',
                'status' => 'rented',
                'serial_number' => 'ISZ-GIGA-2023-11',
                'acquisition_date' => Carbon::parse('2023-11-05'),
                'purchase_price' => 5100000.00,
                'current_value' => 4600000.00,
                'quantity_available' => 3,
                'location' => 'Clark Logistics Depot, Pampanga',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/logistics-yard-support.jpg',
                'specifications' => 'Crane Capacity: 15 t @ 2.5m | Max Radius: 22 m | Payload Deck: 15 t capacity (8.2m length) | 6UZ1 380HP Engine',
                'maximum_load' => 15.00,
                'maximum_load_unit' => 'tons',
                'maximum_radius' => 22.00,
                'maximum_radius_unit' => 'm',
                'final_height' => 25.00,
                'final_height_unit' => 'm',
                'rental_services' => ['operator_and_riggers', 'logistic'],
            ],
            [
                'code' => 'ALIB-LOG-HINO-700',
                'name' => 'Hino 700 Series 60-Ton Lowbed Heavy Hauler',
                'crane_model' => 'Hino 700 6x4 Tractor Head',
                'category' => 'transportation',
                'crane_category' => 'heavy_transporter',
                'description' => 'Multi-axle heavy lowbed trailer combination for transporting tower crane base sections, counterweights, and heavy crawler machines.',
                'rental_rate' => 24000.00,
                'rental_unit' => 'day',
                'status' => 'available',
                'serial_number' => 'HN-700-2023-08',
                'acquisition_date' => Carbon::parse('2023-08-15'),
                'purchase_price' => 6200000.00,
                'current_value' => 5600000.00,
                'quantity_available' => 2,
                'location' => 'Alibaton Equipment Depot, Quezon City Yard',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/logistics-yard-support.jpg',
                'specifications' => 'Gross Combination Mass: 60 t | 3-Axle Detachable Gooseneck Lowbed Trailer | 450HP Common Rail Turbo Diesel',
                'maximum_load' => 60.00,
                'maximum_load_unit' => 'tons',
                'rental_services' => ['operator_and_riggers', 'logistic'],
            ],

            // =========================================================================
            // 7. HEAVY EARTHMOVING & CIVIL EQUIPMENT
            // =========================================================================
            [
                'code' => 'ALIB-EX-LG922',
                'name' => 'LiuGong CLG922E 22-Ton Hydraulic Excavator',
                'crane_model' => 'LiuGong CLG922E',
                'category' => 'heavy_equipment',
                'crane_category' => 'excavator',
                'description' => '22-Ton robust hydraulic excavator deployed for deep foundation digging, retention wall trenching, and mass earthworks.',
                'rental_rate' => 14000.00,
                'rental_unit' => 'day',
                'status' => 'rented',
                'serial_number' => 'LG-922E-2023-06',
                'acquisition_date' => Carbon::parse('2023-06-25'),
                'purchase_price' => 5400000.00,
                'current_value' => 4800000.00,
                'quantity_available' => 2,
                'location' => 'Maynilad Water Reclamation Site, Paranaque',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/heavy-equipment.jpg',
                'specifications' => 'Operating Weight: 22,000 kg | Bucket Capacity: 1.0 m³ | Cummins QSB6.7 Engine (161 HP) | Kawasaki Hydraulics',
                'maximum_load' => 22.00,
                'maximum_load_unit' => 'tons',
                'rental_services' => ['operator_and_riggers', 'maintenance_and_repair'],
            ],
            [
                'code' => 'ALIB-EX-CAT320',
                'name' => 'Caterpillar 320 GC Hydraulic Excavator',
                'crane_model' => 'CAT 320 GC',
                'category' => 'heavy_equipment',
                'crane_category' => 'excavator',
                'description' => '20-Ton Caterpillar standard hydraulic excavator offering premium fuel efficiency and heavy break-out force for rock breaking.',
                'rental_rate' => 15000.00,
                'rental_unit' => 'day',
                'status' => 'available',
                'serial_number' => 'CAT-320GC-2024-03',
                'acquisition_date' => Carbon::parse('2024-02-14'),
                'purchase_price' => 5900000.00,
                'current_value' => 5500000.00,
                'quantity_available' => 2,
                'location' => 'Valenzuela Heavy Equipment Yard',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/heavy-equipment.jpg',
                'specifications' => 'Operating Weight: 20,500 kg | Cat C4.4 Electronic Engine (146 HP) | Digging Depth: 6.72 m | Heavy Duty Boom & Stick',
                'maximum_load' => 20.00,
                'maximum_load_unit' => 'tons',
                'rental_services' => ['maintenance_and_repair', 'operator_and_riggers'],
            ],
            [
                'code' => 'ALIB-WL-LG856',
                'name' => 'LiuGong CLG856H 5-Ton Wheel Loader',
                'crane_model' => 'LiuGong CLG856H',
                'category' => 'heavy_equipment',
                'crane_category' => 'wheel_loader',
                'description' => 'Heavy 5-Ton wheel loader with 3.0 m³ bucket for batching plant aggregate feed, spoil handling, and site grading.',
                'rental_rate' => 13000.00,
                'rental_unit' => 'day',
                'status' => 'available',
                'serial_number' => 'LG-856H-2023-09',
                'acquisition_date' => Carbon::parse('2023-09-10'),
                'purchase_price' => 4800000.00,
                'current_value' => 4300000.00,
                'quantity_available' => 2,
                'location' => 'Alibaton Equipment Depot, Quezon City Yard',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/heavy-equipment.jpg',
                'specifications' => 'Payload: 5,000 kg | Bucket Capacity: 3.0 m³ | Cummins QSL9.3 Engine (217 HP) | ZF 4WG200 Transmission',
                'maximum_load' => 5.00,
                'maximum_load_unit' => 'tons',
                'rental_services' => ['operator_and_riggers', 'maintenance_and_repair'],
            ],
            [
                'code' => 'ALIB-DZ-KOM-D65',
                'name' => 'Komatsu D65EX-16 Crawler Bulldozer',
                'crane_model' => 'Komatsu D65EX-16',
                'category' => 'heavy_equipment',
                'crane_category' => 'bulldozer',
                'description' => '21-Ton crawler bulldozer equipped with Sigma dozer blade for site clearing, embankment spreading, and civil road formation.',
                'rental_rate' => 19000.00,
                'rental_unit' => 'day',
                'status' => 'rented',
                'serial_number' => 'KM-D65-2023-04',
                'acquisition_date' => Carbon::parse('2023-04-12'),
                'purchase_price' => 7600000.00,
                'current_value' => 6900000.00,
                'quantity_available' => 1,
                'location' => 'Subic-Clark Logistics Corridor Expansion Site',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/heavy-equipment.jpg',
                'specifications' => 'Operating Weight: 20,990 kg | Blade Capacity: 5.61 m³ | Komatsu SAA6D114E Engine (205 HP) | Hydrostatic Steering',
                'maximum_load' => 21.00,
                'maximum_load_unit' => 'tons',
                'rental_services' => ['operator_and_riggers', 'maintenance_and_repair'],
            ],
            [
                'code' => 'ALIB-DT-HOWO-10W',
                'name' => 'Sinotruk HOWO 10-Wheeler Heavy Dump Truck',
                'crane_model' => 'Sinotruk HOWO 371 6x4',
                'category' => 'heavy_equipment',
                'crane_category' => 'dump_truck',
                'description' => 'Heavy 20 CBM dump truck built for mass earthworks hauling, quarry aggregate transport, and foundation spoil disposal.',
                'rental_rate' => 9000.00,
                'rental_unit' => 'day',
                'status' => 'available',
                'serial_number' => 'HOWO-371-2023-12',
                'acquisition_date' => Carbon::parse('2023-12-01'),
                'purchase_price' => 3600000.00,
                'current_value' => 3300000.00,
                'quantity_available' => 4,
                'location' => 'Valenzuela Heavy Equipment Yard',
                'image_url' => 'https://alibaton.com.ph/cms/wp-content/themes/alibaton/assets/images/heavy-equipment.jpg',
                'specifications' => 'Capacity: 20 CBM (25 Tons) | Engine: WD615.47 Euro II (371 HP) | Heavy Hardox-grade steel dump box with front tipping ram',
                'maximum_load' => 25.00,
                'maximum_load_unit' => 'tons',
                'rental_services' => ['operator_and_riggers', 'logistic'],
            ],
        ];

        foreach ($fleet as $item) {
            Equipment::updateOrCreate(['code' => $item['code']], $item);
        }
    }
}
