import React, { useEffect, useState } from 'react';
import { Head } from '@inertiajs/react';
import { Activity, BarChart3, BrainCircuit, CalendarDays, CheckCircle2, ClipboardList, PackageCheck, TrendingUp, Users } from 'lucide-react';
import AppLayout from '../../Layouts/AppLayout';
import { Card, CardBody, CardHeader } from '../../Components/Card';
import { formatPeso } from '../../Utils/currency';

interface Analytics { customer_activity: { inquiries_total: number; active_inquiries: number }; quotation_performance: { total: number; accepted: number; rejected: number; conversion_rate: number }; rental_trends: { active: number; pending: number; overdue: number }; equipment_utilization: { total: number; available: number; rented: number; maintenance: number }; job_orders: Record<string, number>; projects: Record<string, number>; revenue_history: Array<{ month: string; amount: number }>; forecast: { available: boolean; reason?: string; month?: string; predicted_revenue?: number; method?: string }; }

const Metric = ({ label, value, detail, icon, tone = 'blue', delay = '' }: { label: string; value: string | number; detail: string; icon: React.ReactNode; tone?: 'blue' | 'green' | 'yellow' | 'purple'; delay?: string }) => {
  const tones = { blue: 'bg-[#edf3ff] text-[#246bdb] dark:bg-[#203354] dark:text-[#9dc3ff]', green: 'bg-[#eaf9f0] text-[#168a4a] dark:bg-[#163c2b] dark:text-[#9be6b8]', yellow: 'bg-[#fff6d9] text-[#9b7800] dark:bg-[#4a3a0d] dark:text-[#ffe071]', purple: 'bg-[#f1edff] text-[#7156c4] dark:bg-[#32264e] dark:text-[#c8b9ff]' };
  return <div className={`animate-[fadeIn_0.45s_ease-out_both] ${delay} border border-neutral-200 bg-white p-4 shadow-sm dark:border-white/10 dark:bg-[#1b1b1b]`}><div className="flex items-start justify-between"><div><p className="text-xs font-medium text-neutral-500 dark:text-neutral-400">{label}</p><p className="mt-2 text-2xl font-bold text-neutral-950 dark:text-white">{value}</p><p className="mt-1 text-xs text-neutral-500 dark:text-neutral-400">{detail}</p></div><span className={`flex h-9 w-9 items-center justify-center ${tones[tone]}`}>{icon}</span></div></div>;
};

const AiAnalytics = () => {
  const [data, setData] = useState<Analytics | null>(null);
  const [error, setError] = useState('');
  useEffect(() => { fetch('/api/analytics/summary', { headers: { Accept: 'application/json' } }).then(response => response.ok ? response.json() : Promise.reject()).then(setData).catch(() => setError('AI analytics could not be loaded.')); }, []);
  const history = data?.revenue_history ?? [];
  const maxRevenue = Math.max(...history.map(item => item.amount), 1);
  const utilization = data?.equipment_utilization.total ? Math.round(((data.equipment_utilization.rented / data.equipment_utilization.total) * 100)) : 0;
  const operations = [
    { label: 'Active Job Orders', value: data?.job_orders['in-progress'] ?? 0, href: '/job-orders', tone: 'bg-[#246bdb]' },
    { label: 'Pending Rental Requests', value: data?.rental_trends.pending ?? 0, href: '/rental-requirements', tone: 'bg-[#d89a00]' },
    { label: 'Active Projects', value: data?.projects.active ?? 0, href: '/projects', tone: 'bg-[#168a4a]' },
  ];

  return <><Head title="AI Analytics Dashboard" /><AppLayout title="AI Analytics Dashboard"><div className="space-y-5">
    {error && <p className="border border-error-200 bg-error-50 p-3 text-sm text-error-700">{error}</p>}
    <section className="animate-[fadeIn_0.45s_ease-out_both] grid grid-cols-1 overflow-hidden border border-neutral-200 bg-white shadow-sm dark:border-white/10 dark:bg-[#1b1b1b] lg:grid-cols-[1.4fr_0.8fr]"><div className="relative p-6 lg:p-8"><div className="absolute inset-y-0 right-0 hidden w-1/3 bg-[linear-gradient(135deg,transparent_30%,#edf3ff_31%,#edf3ff_42%,transparent_43%)] dark:bg-[linear-gradient(135deg,transparent_30%,#203354_31%,#203354_42%,transparent_43%)] lg:block" /><p className="text-sm font-medium text-[#246bdb] dark:text-[#ffd000]">AI decision support</p><h2 className="mt-2 max-w-xl text-2xl font-bold text-neutral-950 dark:text-white sm:text-3xl">Construction sales intelligence, ready for review.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-neutral-600 dark:text-neutral-300">Live summaries from inquiries, quotations, rentals, job orders, equipment, and project records. Insights assist management decisions; they do not replace them.</p><div className="mt-6 flex flex-wrap gap-3 text-xs text-neutral-500 dark:text-neutral-400"><span className="inline-flex items-center gap-1"><CalendarDays className="h-3.5 w-3.5" />Live operating view</span><span className="inline-flex items-center gap-1"><Activity className="h-3.5 w-3.5" />System data only</span></div></div><div className="border-t border-neutral-200 bg-[#f8fafc] p-6 dark:border-white/10 dark:bg-[#202020] lg:border-l lg:border-t-0"><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-full border-4 border-[#edf3ff] text-[#246bdb] dark:border-[#203354] dark:text-[#9dc3ff]"><BrainCircuit className="h-5 w-5" /></div><div><p className="text-sm font-semibold text-neutral-900 dark:text-white">Project success signal</p><p className="text-xs text-neutral-500 dark:text-neutral-400">Based on available operational data</p></div></div><div className="mt-6"><p className="text-4xl font-bold text-neutral-950 dark:text-white">{data?.quotation_performance.conversion_rate ?? 0}<span className="text-base font-medium text-neutral-500">%</span></p><p className="mt-1 text-sm text-neutral-600 dark:text-neutral-300">Quotation conversion rate</p></div><a href="/crm/quotations" className="mt-6 inline-flex text-sm font-medium text-[#246bdb] dark:text-[#ffd000]">Review quotations →</a></div></section>
    <section className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Customer inquiries" value={data?.customer_activity.inquiries_total ?? 0} detail={`${data?.customer_activity.active_inquiries ?? 0} active conversations`} icon={<Users className="h-4 w-4" />} delay="[animation-delay:40ms]" /><Metric label="Quote conversion" value={`${data?.quotation_performance.conversion_rate ?? 0}%`} detail={`${data?.quotation_performance.accepted ?? 0} accepted proposals`} icon={<TrendingUp className="h-4 w-4" />} tone="green" delay="[animation-delay:80ms]" /><Metric label="Active rentals" value={data?.rental_trends.active ?? 0} detail={`${data?.rental_trends.overdue ?? 0} overdue rental(s)`} icon={<PackageCheck className="h-4 w-4" />} tone="yellow" delay="[animation-delay:120ms]" /><Metric label="Equipment utilization" value={`${utilization}%`} detail={`${data?.equipment_utilization.rented ?? 0} of ${data?.equipment_utilization.total ?? 0} currently rented`} icon={<BarChart3 className="h-4 w-4" />} tone="purple" delay="[animation-delay:160ms]" /></section>
    <section className="grid grid-cols-1 gap-5 xl:grid-cols-[1.4fr_0.8fr]"><Card><CardHeader title="Revenue trajectory" subtitle="Completed job orders and rentals only." /><CardBody>{history.length ? <div className="flex h-64 items-end gap-3 border-b border-neutral-200 pb-7 dark:border-white/10">{history.map((item, index) => <div className="group flex h-full min-w-0 flex-1 flex-col justify-end gap-2" key={item.month}><span className="text-center text-[10px] font-medium text-neutral-500 opacity-0 transition-opacity group-hover:opacity-100 dark:text-neutral-400">{formatPeso(item.amount)}</span><div className="relative min-h-1 overflow-hidden bg-[#edf3ff] dark:bg-[#203354]"><div className="absolute inset-x-0 bottom-0 bg-[#246bdb] transition-all duration-700 dark:bg-[#ffd000]" style={{ height: `${Math.max((item.amount / maxRevenue) * 100, 2)}%`, transitionDelay: `${index * 70}ms` }} /></div><span className="text-center text-[10px] text-neutral-500 dark:text-neutral-400">{item.month.slice(5)}</span></div>)}</div> : <div className="flex h-64 items-center justify-center text-sm text-neutral-500">No completed revenue records yet.</div>}</CardBody></Card><Card><CardHeader title="Forecast" subtitle="Decision support based on completed revenue." /><CardBody>{data?.forecast.available ? <><p className="text-3xl font-bold text-neutral-950 dark:text-white">{formatPeso(data.forecast.predicted_revenue)}</p><p className="mt-2 text-sm text-neutral-500 dark:text-neutral-400">Projected for {data.forecast.month}</p><div className="mt-5 border-l-2 border-[#246bdb] pl-3 text-sm text-neutral-600 dark:border-[#ffd000] dark:text-neutral-300">{data.forecast.method}</div></> : <div className="flex h-40 items-center text-sm leading-6 text-neutral-500 dark:text-neutral-400">{data?.forecast.reason || 'Loading forecast conditions...'}</div>}</CardBody></Card></section>
    <section className="grid grid-cols-1 gap-5 lg:grid-cols-3"><Card><CardHeader title="Operational pulse" subtitle="Core 1 status signals" /><CardBody><div className="space-y-4">{operations.map(item => <a href={item.href} className="flex items-center justify-between" key={item.label}><div className="flex items-center gap-3"><span className={`h-2.5 w-2.5 rounded-full ${item.tone}`} /><span className="text-sm text-neutral-600 dark:text-neutral-300">{item.label}</span></div><span className="text-lg font-semibold text-neutral-900 dark:text-white">{item.value}</span></a>)}</div></CardBody></Card><Card><CardHeader title="Sales signals" /><CardBody><div className="space-y-3"><p className="flex justify-between text-sm"><span className="text-neutral-500">Accepted quotations</span><strong className="dark:text-white">{data?.quotation_performance.accepted ?? 0}</strong></p><p className="flex justify-between text-sm"><span className="text-neutral-500">Rejected quotations</span><strong className="dark:text-white">{data?.quotation_performance.rejected ?? 0}</strong></p><p className="flex justify-between text-sm"><span className="text-neutral-500">Equipment maintenance</span><strong className="dark:text-white">{data?.equipment_utilization.maintenance ?? 0}</strong></p></div></CardBody></Card><Card><CardHeader title="Recommended review" /><CardBody><div className="space-y-3 text-sm text-neutral-600 dark:text-neutral-300"><p className="flex gap-2"><CheckCircle2 className="h-4 w-4 shrink-0 text-[#168a4a] dark:text-[#9be6b8]" />Review active inquiries before quotation turnaround.</p><p className="flex gap-2"><ClipboardList className="h-4 w-4 shrink-0 text-[#246bdb] dark:text-[#9dc3ff]" />Check rentals approaching their requested period.</p><a href="/reports" className="inline-flex pt-2 font-medium text-[#246bdb] dark:text-[#ffd000]">Open reports →</a></div></CardBody></Card></section>
  </div></AppLayout></>;
};

export default AiAnalytics;