import React, { useEffect, useState } from 'react';
import { Head } from '@inertiajs/react';
import { History, Search } from 'lucide-react';
import AppLayout from '../../Layouts/AppLayout';
import { Card, CardBody, CardHeader } from '../../Components/Card';
import Button from '../../Components/Button';

interface Inquiry { id: number; inquiry_number: string; subject: string; source: string; status: string; priority: string; customer?: { name: string; company_name?: string }; history?: Array<{ id: number; action: string; notes?: string; created_at: string }>; }
const display = (value?: string) => value ? value.replaceAll('_', ' ').replace(/\b\w/g, letter => letter.toUpperCase()) : '-';

const CRM = () => {
  const [inquiries, setInquiries] = useState<Inquiry[]>([]); const [search, setSearch] = useState(''); const [error, setError] = useState('');
  useEffect(() => { const query = new URLSearchParams({ per_page: '50', ...(search ? { search } : {}) }); fetch(`/api/customer-inquiries?${query}`, { headers: { Accept: 'application/json' } }).then(response => response.ok ? response.json() : Promise.reject()).then(data => { setInquiries(data.data ?? []); setError(''); }).catch(() => setError('CRM inquiries could not be loaded.')); }, [search]);
  return <><Head title="Customer Relationship Management" /><AppLayout dark={true} title="Customer Relationship Management" headerAction={<Button onClick={() => window.location.href = '/crm/quotations'}>Sales & Quotations</Button>}><div className="space-y-5"><Card><CardBody><div className="relative max-w-xl"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-zinc-600" /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search inquiry number, subject, or customer details" className="w-full border border-border-default py-2.5 pl-10 pr-3 text-sm bg-surface-input text-white focus:border-brand focus:ring-1 focus:ring-brand outline-none rounded-md" /></div></CardBody></Card>{error && <p className="border border-error-200 bg-error-50 p-3 text-sm text-error-700">{error}</p>}<div className="grid grid-cols-1 gap-4 lg:grid-cols-2">{inquiries.map(inquiry => <Card key={inquiry.id}><CardHeader title={inquiry.subject} subtitle={`${inquiry.inquiry_number} · ${inquiry.customer?.company_name || inquiry.customer?.name || 'Unassigned customer'}`} action={<span className="border border-border-subtle px-2 py-1 text-xs bg-surface-input text-white focus:border-brand focus:ring-1 focus:ring-brand outline-none rounded-md">{display(inquiry.status)}</span>} /><CardBody><div className="grid grid-cols-2 gap-3 text-sm"><p><span className="text-content-secondary">Source</span><br />{display(inquiry.source)}</p><p><span className="text-content-secondary">Priority</span><br />{display(inquiry.priority)}</p></div><div className="mt-4 border-t border-border-subtle pt-3 bg-surface-input text-white focus:border-brand focus:ring-1 focus:ring-brand outline-none rounded-md"><p className="flex items-center gap-2 text-sm font-medium text-content-primary"><History className="h-4 w-4" />Interaction history</p>{(inquiry.history ?? []).slice(0, 3).map(item => <p className="mt-2 text-sm text-content-secondary" key={item.id}>{display(item.action)}: {item.notes || 'No notes recorded'}</p>)}{!inquiry.history?.length && <p className="mt-2 text-sm text-content-secondary">No interaction history recorded.</p>}</div></CardBody></Card>)}</div>{!error && !inquiries.length && <p className="py-12 text-center text-sm text-content-secondary">No inquiries found. Create client inquiries through the CRM API to begin the sales workflow.</p>}</div></AppLayout></>;
};
export default CRM;